// Global using directives

global using Castle.DynamicProxy;
global using EasySoft.Core.ChannelCheckTransmitter.Extensions;
global using EasySoft.Core.Config.ConfigAssist;
global using EasySoft.Core.Infrastructure.Assists;
global using EasySoft.Core.Infrastructure.Configures;
global using EasySoft.Core.Infrastructure.Startup;
global using EasySoft.Core.Refit.ExtensionMethods;
global using EasySoft.UtilityTools.Core.Attributes;
global using EasySoft.UtilityTools.Core.Channels;
global using EasySoft.UtilityTools.Core.Extensions;
global using EasySoft.UtilityTools.Core.Interceptors;
global using EasySoft.UtilityTools.Core.Results;
global using EasySoft.UtilityTools.Standard.Assists;
global using EasySoft.UtilityTools.Standard.Attributes;
global using EasySoft.UtilityTools.Standard.DataTransferObjects;
global using EasySoft.UtilityTools.Standard.Entities.Interfaces;
global using EasySoft.UtilityTools.Standard.Exceptions;
global using EasySoft.UtilityTools.Standard.Extensions;
global using EasySoft.UtilityTools.Standard.Notifications;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Refit;