// <auto-generated />
using EasySoft.Simple.Tradition.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasySoft.Simple.Tradition.Data.Migrations
{
    [DbContext(typeof(SqlServerDataContext))]
    partial class SqlServerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EasySoft.Core.Infrastructure.Repositories.Entities.Implementations.EventTracker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("数据标识");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id")
                        .HasComment("事件标识");

                    b.Property<string>("TrackerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tracker_name")
                        .HasComment("跟踪名称");

                    b.HasKey("Id")
                        .HasName("pk_event_tracker");

                    b.ToTable("event_tracker", (string)null);

                    b.HasComment("事件跟踪");
                });

            modelBuilder.Entity("EasySoft.Simple.Tradition.Data.Entities.Blog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("数据标识");

                    b.Property<string>("Motto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("motto")
                        .HasComment("座右铭");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("name")
                        .HasComment("名称");

                    b.Property<string>("Pseudonym")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("pseudonym")
                        .HasComment("笔名");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_id")
                        .HasComment("用户标识");

                    b.HasKey("Id")
                        .HasName("pk_blog");

                    b.ToTable("blog", (string)null);

                    b.HasComment("博客");

                    b.HasData(
                        new
                        {
                            Id = 364366116073479L,
                            Motto = "",
                            Name = "",
                            Pseudonym = "",
                            UserId = 364366116073478L
                        });
                });

            modelBuilder.Entity("EasySoft.Simple.Tradition.Data.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("数据标识");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_id")
                        .HasComment("用户标识");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer", (string)null);

                    b.HasComment("顾客信息");

                    b.HasData(
                        new
                        {
                            Id = 364366116073478L,
                            UserId = 364366116073477L
                        });
                });

            modelBuilder.Entity("EasySoft.Simple.Tradition.Data.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("数据标识");

                    b.Property<long>("BlogId")
                        .HasColumnType("bigint")
                        .HasColumnName("blog_id")
                        .HasComment("");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("title")
                        .HasComment("");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("BlogId")
                        .HasDatabaseName("ix_post_blog_id");

                    b.ToTable("post", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 364366116073480L,
                            BlogId = 364366116073479L,
                            Title = "5cb3e93dd7b84a2bb238bdd80fafa31b"
                        },
                        new
                        {
                            Id = 364366116073481L,
                            BlogId = 364366116073479L,
                            Title = "c039271ed1a14a51ac26da13f8c900c3"
                        },
                        new
                        {
                            Id = 364366116073482L,
                            BlogId = 364366116073479L,
                            Title = "11141e9cb3b9425ca3499cc112583e6e"
                        });
                });

            modelBuilder.Entity("EasySoft.Simple.Tradition.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("数据标识");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("alias")
                        .HasComment("别名");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("login_name")
                        .HasComment("登录名");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("password")
                        .HasComment("密码");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("real_name")
                        .HasComment("真实姓名");

                    b.Property<long>("RoleGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_group_id")
                        .HasComment("");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);

                    b.HasComment("基础账户");

                    b.HasData(
                        new
                        {
                            Id = 364366116073477L,
                            Alias = "种子用户",
                            LoginName = "first",
                            Password = "e10adc3949ba59abbe56e057f20f883e",
                            RealName = "张小明",
                            RoleGroupId = 1L
                        });
                });

            modelBuilder.Entity("EasySoft.Simple.Tradition.Data.Entities.Post", b =>
                {
                    b.HasOne("EasySoft.Simple.Tradition.Data.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_blog_blog_id");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("EasySoft.Simple.Tradition.Data.Entities.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
