version: "3"

services:
  easy_soft_envoy:
    image: envoyproxy/envoy:latest
    #    image: envoyproxy/envoy:v1.14.2
    #    build:
    #      context: ./
    #      dockerfile: Dockerfile
    container_name: easy_soft_envoy
    restart: always
    network_mode: bridge
    ports:
      - "9901:9901"
      - "10000:10000"
      - "15001:15001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
