// Global using directives

global using System.Reflection;
global using Autofac;
global using EasySoft.Core.AuthenticationCore.Operators;
global using EasySoft.Core.Data.ExtensionMethods;
global using EasySoft.Core.Data.Repositories;
global using EasySoft.Core.EntityFramework.EntityConfigures.Implementations;
global using EasySoft.Core.EntityFramework.EntityTypeConfigures;
global using EasySoft.Core.EventBus;
global using EasySoft.Core.Infrastructure.Assists;
global using EasySoft.Core.Permission.Server.Services.Interfaces;
global using EasySoft.Core.PermissionVerification.Detectors;
global using EasySoft.Core.PermissionVerification.ExtensionMethods;
global using EasySoft.Core.PermissionVerification.Middlewares;
global using EasySoft.Core.PermissionVerification.Observers;
global using EasySoft.Core.PermissionVerification.Officers;
global using EasySoft.UtilityTools.Core.ExtensionMethods;
global using EasySoft.UtilityTools.Standard;
global using EasySoft.UtilityTools.Standard.Assists;
global using EasySoft.UtilityTools.Standard.Competence;
global using EasySoft.UtilityTools.Standard.ExtensionMethods;
global using Mapster;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Newtonsoft.Json;